/* Healthcare Requirements Management — Embedded Data */

const REQUIREMENTS_DATA = [
  { id: "REQ-001", description: "Unique user identification for all ePHI access", source: "HIPAA Security Rule §164.312(a)(2)(i)", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-002", description: "Multi-factor authentication (MFA) for all ePHI access points", source: "OCR 2025 Rule", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-003", description: "Encryption at rest for all ePHI", source: "HIPAA Security Rule §164.312(a)(2)(iv)", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-004", description: "Encryption in transit for all ePHI", source: "HIPAA Security Rule §164.312(e)(1)", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-005", description: "Security Risk Analysis (SRA) conducted and documented", source: "OCR Enforcement Initiative 2025", category: "Privacy/Security", priority: "High", owner: "Compliance Officer", status: "Not Started" },
  { id: "REQ-006", description: "BAA with all vendors that handle PHI", source: "HIPAA Privacy Rule §164.308(b)(1)", category: "Privacy/Security", priority: "High", owner: "Compliance Officer", status: "Not Started" },
  { id: "REQ-007", description: "Audit logging for ePHI access", source: "HIPAA Security Rule §164.312(b)", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-008", description: "Third-party tracking tools (pixels, chat) assessed for PHI exposure", source: "OCR 2025 Rule", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-009", description: "Workforce HIPAA training (role-based, documented)", source: "HIPAA Privacy Rule §164.530(b)", category: "Operations", priority: "High", owner: "HR/Compliance", status: "Not Started" },
  { id: "REQ-010", description: "Incident response and breach notification plan", source: "HITECH Breach Notification", category: "Privacy/Security", priority: "High", owner: "Compliance Officer", status: "Not Started" },
  { id: "REQ-011", description: "Minimum necessary standard for PHI disclosures", source: "HIPAA Privacy Rule §164.502(b)", category: "Privacy/Security", priority: "High", owner: "Privacy Officer", status: "Not Started" },
  { id: "REQ-012", description: "Patient rights (access, amendment, accounting of disclosures)", source: "HIPAA Privacy Rule §164.524-528", category: "Operations", priority: "High", owner: "Privacy Officer", status: "Not Started" },
  { id: "REQ-013", description: "Price transparency compliance (if applicable)", source: "CMS Hospital Price Transparency", category: "Operations", priority: "Medium", owner: "Billing/Finance", status: "Not Started" },
  { id: "REQ-014", description: "Medical necessity documentation for billed services", source: "CMS Conditions of Participation", category: "Billing", priority: "High", owner: "Billing Manager", status: "Not Started" },
  { id: "REQ-015", description: "Accurate coding per CPT/ICD guidelines", source: "CMS Billing Rules", category: "Billing", priority: "High", owner: "Billing Manager", status: "Not Started" },
  { id: "REQ-016", description: "Contingency plan - critical data restored within 72 hours", source: "HIPAA Security Rule §164.308(a)(7)", category: "Privacy/Security", priority: "High", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-017", description: "Workstation and device security (screen locks, encryption)", source: "HIPAA Security Rule §164.310", category: "Privacy/Security", priority: "Medium", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-018", description: "Physical access controls and visitor logs", source: "HIPAA Security Rule §164.310(a)(1)", category: "Privacy/Security", priority: "Medium", owner: "Facilities", status: "Not Started" },
  { id: "REQ-019", description: "Secure disposal of PHI and devices", source: "HIPAA Security Rule §164.310(d)(2)", category: "Privacy/Security", priority: "Medium", owner: "IT/Security", status: "Not Started" },
  { id: "REQ-020", description: "Compliance Committee with charter and meeting records", source: "OIG 7 Elements", category: "Operations", priority: "High", owner: "Compliance Officer", status: "Not Started" }
];

const TRACEABILITY_DATA = [
  { reqId: "REQ-001", policy: "POL-SEC-02 Access Control Policy", control: "EHR user provisioning; unique IDs per user", evidence: "Monthly access review report" },
  { reqId: "REQ-002", policy: "POL-SEC-03 Authentication Policy", control: "MFA enabled on EHR; VPN; patient portal", evidence: "IT configuration audit" },
  { reqId: "REQ-003", policy: "POL-SEC-04 Encryption Policy", control: "Database encryption; file-level encryption", evidence: "Encryption audit report" },
  { reqId: "REQ-004", policy: "POL-SEC-04 Encryption Policy", control: "TLS for all PHI transmission; secure messaging", evidence: "Network security scan" },
  { reqId: "REQ-005", policy: "POL-SEC-01 Risk Management", control: "SRA conducted annually; threats/vulnerabilities documented", evidence: "SRA document; remediation plan" },
  { reqId: "REQ-006", policy: "POL-PRIV-01 Business Associates", control: "BAA template; vendor inventory with BAA status", evidence: "BAA log; vendor list" },
  { reqId: "REQ-007", policy: "POL-SEC-05 Audit Logging", control: "Logging enabled on EHR; access logs retained", evidence: "Audit log sample; retention policy" },
  { reqId: "REQ-008", policy: "POL-SEC-06 Marketing/Tracking", control: "Website audit; BAA for tracking tools that touch PHI", evidence: "Tracking tool inventory" },
  { reqId: "REQ-009", policy: "POL-TRAIN-01 Workforce Training", control: "LMS; role-based modules; completion tracking", evidence: "Training completion report" },
  { reqId: "REQ-010", policy: "POL-SEC-07 Incident Response", control: "IR plan; breach notification procedures", evidence: "IR plan document; drill log" }
];

const STEPS_DATA = [
  { num: 1, title: "Define Scope and Stakeholders", summary: "Map stakeholders (Executive Sponsor, CCO, CMO, Legal, IT, Finance, HR). Scope: clinical, billing, privacy/security, operations.", body: "<p>Stakeholder engagement is <strong>not just a best practice — it's a necessity.</strong></p><h4>Stakeholder Map</h4><ul><li>Executive Sponsor (Alison) — final sign-off</li><li>CCO — program ownership, audit coordination</li><li>CMO — clinical workflows, patient safety</li><li>Legal, IT/Security, Finance/Billing, HR, Patient Advocate, Ethics Officer</li></ul><h4>Scope Areas</h4><ul><li>Clinical workflows (intake, documentation, telehealth)</li><li>Billing and revenue cycle</li><li>Privacy & security</li><li>Operations (scheduling, referrals, records)</li></ul>" },
  { num: 2, title: "Regulatory and Compliance Obligations", summary: "OCR 2025: 10 resolution agreements in 5 months. Mandatory MFA, encryption, tracking tool BAAs.", body: "<p><strong>2025–2026 Key Updates:</strong></p><ul><li>Mandatory MFA across all ePHI access points</li><li>Mandatory encryption at rest and in transit</li><li>Third-party tracking (pixels, chat) requires BAAs</li><li>HITECH PHI disclosure tracking</li><li>Hospital price transparency (46% non-compliance)</li></ul><h4>Regulatory Map</h4><p>HIPAA Privacy/Security, HITECH, 21st Century Cures Act, CMS/Medicare/Medicaid, state laws, accreditation (Joint Commission, NCQA, URAC).</p>" },
  { num: 3, title: "Document Current State", summary: "Complete technology asset inventory and PHI flow map. Document lifecycle: creation → storage → use → sharing → retention → disposal.", body: "<p>2025 HIPAA Security Rule requires a <strong>complete technology asset inventory and network map</strong> of ePHI movement.</p><h4>Document Lifecycle</h4><ol><li>Creation — forms, calls, EHR entries</li><li>Storage — servers, cloud, devices</li><li>Use — who accesses, for what</li><li>Sharing — labs, payers, portals, vendors</li><li>Retention — how long, where</li><li>Disposal — secure deletion</li></ol><p>Contingency: critical data restored within <strong>72 hours</strong>.</p>" },
  { num: 4, title: "Create a Requirements Repository", summary: "VComply, Scrut, ComplyJet, Accountable HQ, or Notion/Airtable. Standard fields: ID, Description, Source, Category, Priority, Owner, Status, Evidence.", body: "<p><strong>Platforms:</strong> VComply (HIPAA templates), Scrut (1,400+ controls), ComplyJet (EHR integration), Accountable HQ, Notion/Airtable.</p><h4>Standard Fields</h4><p>ID, Description, Source, Category, Priority, Owner, Status, Evidence/Link.</p><h4>Automation Ideas</h4><ul><li>Policy routing for approval</li><li>Auto-assign training on publish</li><li>Trigger risk assessments for new PHI systems</li></ul><p>Pre-seed: 20–30 HIPAA, 10–15 billing, 10–15 operational requirements.</p>" },
  { num: 5, title: "Prioritize Requirements", summary: "Score 1–3 on: Regulatory risk, Patient safety, Business impact, Urgency. Top 5 priorities: emerging tech, privacy, quality, billing, vendor management.", body: "<p><strong>Scoring (1–3 each):</strong> Regulatory risk, Patient safety impact, Business impact, Urgency/deadline. Sum and sort highest to lowest.</p><h4>Immediate High-Urgency</h4><ul><li>Enterprise-wide risk analysis (OCR enforcing)</li><li>Mandatory MFA</li><li>Encryption at rest and in transit</li><li>Third-party tracking tool audit</li><li>Price transparency compliance</li></ul>" },
  { num: 6, title: "Implement HIPAA and Privacy Safeguards", summary: "Administrative, Technical, Physical. MFA, encryption, SRA, BAAs, audit logging, 72-hour recovery.", body: "<p><strong>Administrative:</strong> Privacy/Security Officers, SRA, role-based access, workforce training, BAAs.</p><p><strong>Technical:</strong> Mandatory MFA (2025), encryption, audit logging, RBAC, backup/DR (72 hours), tracking tool assessment.</p><p><strong>Physical:</strong> Server/workstation access, visitor logs, workstation positioning, device tracking/encryption, disposal procedures.</p><p>Deliverable: HIPAA Safeguard Register + SRA summary.</p>" },
  { num: 7, title: "Set Up a Governance Process", summary: "Formal Compliance Committee with charter, annual schedule, attendance records. Unify GRC. Route new systems/vendors through committee.", body: "<p>Every organization needs a <strong>formal Compliance Committee</strong> with written charter, annual meeting schedule, and attendance records.</p><h4>Membership</h4><p>CCO (lead), Legal, CMO/CNO, IT/Security, Finance/Billing, HR/Ethics, Department Managers.</p><h4>Framework</h4><ul><li>Unify GRC (Governance + Risk + Compliance)</li><li>Change process: route every new system/vendor through committee</li><li>Governance Log: decisions, owners, dates</li></ul>" },
  { num: 8, title: "Build Traceability", summary: "RTM: Requirement → Policy → Control → Evidence. Version control, immutable audit trails, attach evidence to controls.", body: "<p>RTM provides <strong>a transparent chain of evidence for regulators</strong>.</p><h4>Structure</h4><p>Requirement ID → Policy/Procedure → Control/Implementation → Evidence/Report</p><h4>Evidence Artifacts</h4><p>Access matrices, audit logs, data maps, incident logs, training records, BAAs, policy revision histories.</p><h4>Best Practices</h4><ul><li>Version control for policies</li><li>Immutable audit trails</li><li>Attach evidence to controls</li><li>Periodic review</li></ul>" },
  { num: 9, title: "Plan Audits and Monitoring", summary: "OIG 7 elements. Internal audits: access control, telehealth, billing, marketing. KPIs: security, privacy, operations.", body: "<p><strong>OIG 7 Elements:</strong> Policies, Leadership, Training, Communication, Monitoring/audit, Enforcement, Corrective action.</p><h4>2025–2026 Context</h4><p>FCA settlements historic highs; OIG $450M+ funding; breaches $7.42M avg; HIPAA $100–$50K per violation.</p><h4>Internal Audit Plan</h4><p>Access control, telehealth workflows, billing documentation, marketing data collection.</p><h4>KPIs</h4><p>Security (violations, logins, inactive accounts), Privacy (incidents, response times), Operations (record requests, no-shows).</p><p>Move beyond reactive monitoring into <strong>proactive, documented risk management</strong>.</p>" },
  { num: 10, title: "Train and Communicate", summary: "Role-based HIPAA training, documented. Cybersecurity now explicitly required (300% attack increase). 67% of 2024 violations cited inadequate training.", body: "<p><strong>HIPAA Training (2025):</strong> Role-based, comprehensive, ongoing, documented.</p><h4>Required Topics</h4><p>PHI definition, Privacy Rule basics, breach reporting, sanctions. Security: cyber threats, phishing, passwords, mobile/email.</p><h4>2025 Emphasis</h4><p>Cybersecurity training explicitly required — healthcare cyberattacks up <strong>300%</strong>.</p><h4>Attestation</h4><p>Signed statement for PHI use/disclosure compliance. Required for sensitive care, judicial, law enforcement, oversight.</p><p>2024: OCR $28M+ penalties; <strong>67% of violations</strong> cited inadequate workforce training.</p>" }
];
